server = true
data = true
clients = true
stats = true
cpu = true
replication = true
keyspace = true
cache = false
commandp99 = true
slowcommand = true
execcount = false
commandstats = false
rocksdb = false
