# tbb
FETCHCONTENT_DECLARE(
        tbb
        GIT_REPOSITORY https://github.com/oneapi-src/oneTBB.git
        GIT_TAG v2020.1
)

SET(TBB_BUILD_STATIC ON CACHE BOOL "" FORCE)
SET(TBB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
SET(TBB_BUILD_TESTS OFF CACHE BOOL "" FORCE)
SET(TBB_BUILD_TESTS_DEPENDENCIES OFF CACHE BOOL "" FORCE)
FETCHCONTENT_MAKEAVAILABLE(tbb)